// Generated by CoffeeScript 1.9.2
(function() {
  var c1, c2, i, j, k, l, len, len1, name, ref, res, uls;

  name = "select";

  res = [];

  uls = document.getElementsByTagName("ul");

  c1 = 0;

  c2 = 0;

  for (k = 0, len = uls.length; k < len; k++) {
    i = uls[k];
    c1++;
    c2 = 0;
    ref = i.childNodes;
    for (l = 0, len1 = ref.length; l < len1; l++) {
      j = ref[l];
      c2++;
      if (j.checked === true) {
        res.push({
          "item": c1,
          "result": c2 / 2
        });
      }
    }
  }

  console.log(JSON.stringify(res));

}).call(this);
